name: Bug report
description: Report a bug
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and expected behavior.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version/commit
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
  - type: textarea
    id: logs
    attributes:
      label: Logs
      render: bash

